config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks, only: [:index, :new, :create, :edit, :update]

  root to: 'bookmarks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  VALID_URL_FORMAT = /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix

  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  include PgSearch

  belongs_to :site

  validates :title, :url, :site, presence: true
  validates :url, format: VALID_URL_FORMAT

  pg_search_scope :search, against: [:title, :url, :shortening, :tags],
                           using: {
                            tsearch: { prefix: true }
                          }
end

app/models/site.rb
class Site < ApplicationRecord
  validates :url, presence: true
  validates :url, format: VALID_URL_FORMAT
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found_response

  def render_not_found_response
    render file: "#{Rails.root}/public/404.html", layout: false, :status => 404
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.order(created_at: :desc)
    @bookmarks = @bookmarks.search(params[:q]) if params[:q].present?
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    if factory.create
      redirect_to bookmarks_url, notice: 'Bookmark was successfully created.'
    else
      @bookmark = factory.bookmark
      render :new
    end
  end

  def edit
    bookmark
  end

  def update
    if factory.update(bookmark)
      redirect_to bookmarks_url, notice: 'Bookmark was successfully updated.'
    else
      render :edit
    end
  end

  private

  def factory
    @factory ||= BookmarkFactory.new(bookmark_params)
  end

  def bookmark
    @bookmark ||= Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:title, :url, :shortening, :tags)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
  def tags_inline(bookmark)
    bookmark.tags.join(', ')
  end
end

app/views/bookmarks/_form.html.erb
<div class="form-group">
  <%= f.label :title, class: 'col-sm-2 control-label' %>
  <div class='col-sm-6'>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :url, class: 'col-sm-2 control-label' %>
  <div class='col-sm-6'>
    <%= f.text_field :url, class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :shortening, class: 'col-sm-2 control-label' %>
  <div class='col-sm-6'>
    <%= f.text_area :shortening, class: 'form-control', rows: 4 %>
  </div>
</div>
<div class="form-group">
  <%= f.label :tags, class: 'col-sm-2 control-label' %>
  <div class='col-sm-6'>
    <%= f.text_area :tags, class: 'form-control', rows: 4, value: tags_inline(f.object) %>
    <p class="help-block">Please use "," (comma) to separate tags.</p>
  </div>
</div>
<%= f.submit 'Save', class: 'btn btn-success' %>
<%= link_to 'Back', :back %>

app/views/bookmarks/edit.html.erb
<h3>Edit bookmark</h3>
<hr />
<%= form_for @bookmark, html: { class: 'form-horizontal' } do |f| %>
  <%= render 'shared/errors', target: @bookmark %>
  <%= render 'form', f: f %>
<% end %>

app/views/bookmarks/index.html.erb
<% unless @bookmarks.empty? %>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th>Title</th>
        <th>URL</th>
        <th>Site</th>
        <th>Shortening</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.title %></td>
        <td><%= bookmark.url %></td>
        <td><%= bookmark.site.url %></td>
        <td><%= bookmark.shortening %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark), class: 'btn btn-info btn-sm' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/bookmarks/new.html.erb
<h3>Add bookmark</h3>
<hr />
<%= form_for @bookmark, html: { class: 'form-horizontal' } do |f| %>
  <%= render 'shared/errors', target: @bookmark %>
  <%= render 'form', f: f %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bookmarkable" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Bookmarkable', root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <%= form_tag bookmarks_path, method: :get, class: 'navbar-form navbar-right' do %>
            <%= link_to 'Add Bookmark', new_bookmark_path, class: 'btn btn-primary' %>
            <div class="form-group">
              <%= text_field_tag 'q', params[:q], placeholder: 'Search bookmarks', class: 'form-control' %>
            </div>
            <%= button_tag class: 'btn btn-success' do %>
              <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
            <% end %>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>

      <footer>
        <p>&copy; Tiago Lupepic 2017</p>
      </footer>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if target.errors.present? %>
<div class="alert alert-danger">
  <p><strong>Please check the following fields:</strong></p>
  <ul>
  <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>